import { useEffect, useMemo, useRef, useState } from 'react'
import MissionShell from '../components/MissionShell'

const clamp = (n, a, b) => Math.max(a, Math.min(b, n))
const path = (points, sx, sy) => points.map((p) => `${sx(p.x)},${sy(p.y)}`).join(' ')

function Bench({ kind }) {
  const colors = { ohm: '#f97316', pendulum: '#0ea5e9', projectile: '#f43f5e', hysteresis: '#8b5cf6', diode: '#22c55e', slit: '#eab308' }
  const accent = colors[kind] || '#38bdf8'
  return (
    <div className="h-44 overflow-hidden rounded-xl border border-slate-700 bg-slate-950 p-4 flex flex-col justify-between relative shadow-inner">
      <div className="flex justify-between items-center z-10">
        <span className="text-[11px] font-mono tracking-widest text-slate-400 uppercase font-semibold">Laboratory Workstation Bench</span>
        <span className="inline-flex items-center gap-1.5 text-[10px] font-mono text-emerald-400 bg-emerald-950/60 border border-emerald-800 px-2 py-0.5 rounded-full">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-ping"></span> ONLINE
        </span>
      </div>
      <div className="relative flex-1 flex items-center justify-center">
        <svg viewBox="0 0 360 90" className="w-full h-full max-w-md drop-shadow-[0_10px_20px_rgba(0,0,0,0.5)]">
          <polygon points="180,10 330,35 180,60 30,35" fill="#1e293b" stroke="#334155" strokeWidth="1.5" />
          <polygon points="30,35 180,60 180,72 30,47" fill="#0f172a" />
          <polygon points="180,60 330,35 330,47 180,72" fill="#1e293b" />
          
          <polygon points="180,22 230,31 180,40 130,31" fill={accent} opacity="0.9" />
          <polygon points="130,31 180,40 180,48 130,39" fill={accent} opacity="0.7" />
          <polygon points="180,40 230,31 230,39 180,48" fill={accent} opacity="0.6" />
          
          <g>
            <ellipse cx="90" cy="30" rx="10" ry="5" fill="#64748b" />
            <rect x="80" y="24" width="20" height="6" fill="#475569" />
            <ellipse cx="90" cy="24" rx="10" ry="5" fill="#94a3b8" />
          </g>
          
          <circle cx="270" cy="33" r="8" fill="#38bdf8" opacity="0.8" />
          <circle cx="270" cy="33" r="12" fill="none" stroke="#38bdf8" strokeWidth="1" strokeDasharray="3 3" opacity="0.5" />
        </svg>
      </div>
      <div className="text-[10px] text-slate-500 font-mono flex justify-between z-10">
        <span>ISO-9001 CALIBRATED</span>
        <span className="text-slate-400">BENCH-READY</span>
      </div>
    </div>
  )
}

function SvgGraph({ title, series, yLabel = 'value', colors = ['#38bdf8', '#f97316'] }) {
  const W = 520, H = 190, P = 30
  const all = series.flatMap(s => s.points)
  const xmax = Math.max(1, ...all.map(p => p.x)); const ymin = Math.min(0, ...all.map(p => p.y)); const ymax = Math.max(1, ...all.map(p => p.y))
  const sx = x => P + x / xmax * (W - P * 2); const sy = y => H - P - (y - ymin) / Math.max(1e-6, ymax - ymin) * (H - P * 2)
  return <div className="rounded-xl border border-slate-200 bg-white p-3"><div className="mb-1 flex justify-between text-xs font-bold text-slate-600"><span>{title}</span><span>{yLabel}</span></div>
    <svg viewBox={`0 0 ${W} ${H}`} className="w-full" role="img" aria-label={title}><path d={`M${P} ${P}V${H-P}H${W-P}`} fill="none" stroke="#cbd5e1" />
      {[.25,.5,.75].map(n => <line key={n} x1={P} x2={W-P} y1={P+n*(H-2*P)} y2={P+n*(H-2*P)} stroke="#e2e8f0" />)}
      {series.map((s, i) => <polyline key={s.name} points={path(s.points, sx, sy)} fill="none" stroke={colors[i]} strokeWidth="2.5" />)}
      {series.map((s, i) => <text key={s.name} x={W - P - i * 82} y={16} fill={colors[i]} fontSize="10">{s.name}</text>)}
    </svg></div>
}

function Palette({ items, placed, setPlaced }) {
  const drop = e => { e.preventDefault(); const item = e.dataTransfer.getData('text/plain'); if (item && !placed.includes(item)) setPlaced([...placed, item]) }
  return <div className="grid grid-cols-1 gap-3 md:grid-cols-2"><div className="rounded-xl bg-slate-900 p-3 text-white"><p className="mb-2 text-xs font-bold uppercase tracking-wider text-slate-400">apparatus tray — drag items</p><div className="flex flex-wrap gap-2">{items.map(x => <button draggable onDragStart={e => e.dataTransfer.setData('text/plain', x)} key={x} className="cursor-grab rounded-md border border-slate-600 bg-slate-800 px-3 py-2 text-xs active:cursor-grabbing">{x}</button>)}</div></div>
    <div onDrop={drop} onDragOver={e => e.preventDefault()} className="min-h-24 rounded-xl border-2 border-dashed border-cyan-300 bg-cyan-50 p-3"><p className="text-xs font-bold text-cyan-800">work surface — drop apparatus here</p><div className="mt-2 flex flex-wrap gap-2">{placed.map(x => <span key={x} className="rounded bg-white px-2 py-1 text-xs shadow-sm">{x} ✓</span>)}</div></div></div>
}

function Frame({ title, emoji, kind, steps, controls, visualization, observations, ready, tutor, records, onRecord }) {
  const mistakes = ready ? [] : ['Setup incomplete: drag the required apparatus onto the work surface before recording readings.']
  return <MissionShell title={title} titleEmoji={emoji} subject="Physics" accentColor="blue" gradientFrom="from-slate-800" gradientTo="to-cyan-700" steps={steps} currentStep={ready ? 3 : 0} observations={observations}
    controls={<div className="space-y-4"><Bench kind={kind} />{controls}<div className="rounded-xl border border-violet-200 bg-violet-50 p-3 text-sm text-violet-950"><b>AI lab tutor</b><p className="mt-1">{tutor}</p></div>{mistakes.map(m => <div key={m} className="rounded-lg bg-amber-50 p-3 text-xs text-amber-800">⚠ {m}</div>)}</div>}
    visualization={<div className="space-y-4">{visualization}<div className="rounded-xl border border-slate-200 bg-white p-3"><div className="mb-2 flex items-center justify-between"><b className="text-sm">Live data collection</b><button onClick={onRecord} disabled={!ready} className="rounded-lg bg-cyan-600 px-3 py-1.5 text-xs font-bold text-white disabled:opacity-40">Record reading</button></div><table className="w-full text-left text-xs"><thead className="text-slate-400"><tr><th>Trial</th><th>Measurement</th><th>Result</th></tr></thead><tbody>{records.length ? records.map((r,i)=><tr key={i} className="border-t"><td className="py-2">{i+1}</td><td>{r.a}</td><td>{r.b}</td></tr>) : <tr><td colSpan="3" className="py-4 text-center text-slate-400">Record a live measurement to build your results table.</td></tr>}</tbody></table></div></div>} />
}

export function OhmsLab() {
  const [placed,setPlaced]=useState([]), [voltage,setVoltage]=useState(6), [resistance,setResistance]=useState(120), [records,setRecords]=useState([])
  const ready=['Battery','Resistor','Ammeter','Voltmeter','Wire'].every(x=>placed.includes(x)); const current=voltage/resistance, power=voltage*current
  const pts=Array.from({length:13},(_,i)=>({x:i*1.5,y:i*1.5/resistance*1000}))
  return <Frame title="Ohm’s Law • circuit bench" emoji="⚡" kind="ohm" ready={ready} records={records} onRecord={()=>setRecords([...records,{a:`${voltage.toFixed(1)} V × ${resistance} Ω`,b:`${(current*1000).toFixed(2)} mA · ${(power*1000).toFixed(1)} mW`}])} steps={[{title:'Place',description:'Drag all apparatus to the bench'},{title:'Wire',description:'Connect each terminal'},{title:'Energize',description:'Turn the supply dial'},{title:'Record',description:'Capture V-I values'}]} observations={['Electron pulses travel through the closed circuit.', 'The resistor glow visualizes P = I²R.']} tutor="Place every instrument, then use the supply and resistor dials. The blue traces represent moving charge." controls={<><Palette items={['Battery','Resistor','Ammeter','Voltmeter','Wire']} placed={placed} setPlaced={setPlaced}/><div className="grid grid-cols-2 gap-2"><label className="text-xs">Battery dial <input className="w-full" type="range" min="1" max="18" value={voltage} onChange={e=>setVoltage(+e.target.value)}/>{voltage} V</label><label className="text-xs">Resistor dial <input className="w-full" type="range" min="20" max="500" value={resistance} onChange={e=>setResistance(+e.target.value)}/>{resistance} Ω</label></div><div className="rounded-lg bg-orange-50 p-2 text-xs">⚡ {ready?'Electron flow active':'Open circuit'} · I {(current*1000).toFixed(1)} mA · <span className={power>.35?'text-red-600 font-bold':''}>heat {(power*1000).toFixed(1)} mW</span></div></>} visualization={<><div className="rounded-xl bg-slate-950 p-4"><div className="h-2 rounded-full bg-slate-800"><div className="h-2 animate-pulse rounded-full bg-cyan-300" style={{width:`${clamp(current*10000,2,100)}%`}} /></div><p className="mt-2 text-xs text-cyan-200">electrons → → → resistor thermal field</p></div><SvgGraph title="Live V–I characteristic" yLabel="current (mA)" series={[{name:'V–I',points:pts},{name:'reading',points:[{x:voltage,y:current*1000}]}]}/></>} />
}

export function PendulumLab(){const [placed,setPlaced]=useState([]),[L,setL]=useState(1),[theta,setTheta]=useState(25),[run,setRun]=useState(false),[t,setT]=useState(0),[records,setRecords]=useState([]); const raf=useRef(); const ready=placed.includes('Bob')&&placed.includes('String'); const period=2*Math.PI*Math.sqrt(L/9.81); useEffect(()=>{if(!run)return;const start=performance.now()-t*1000;const f=n=>{setT((n-start)/1000);raf.current=requestAnimationFrame(f)};raf.current=requestAnimationFrame(f);return()=>cancelAnimationFrame(raf.current)},[run]); const a=run?theta*Math.cos(2*Math.PI*t/period)*Math.exp(-.015*t):theta; const bx=200+125*L*Math.sin(a*Math.PI/180),by=28+125*L*Math.cos(a*Math.PI/180); const graph=Array.from({length:8},(_,i)=>({x:.3+i*.2,y:(2*Math.PI*Math.sqrt((.3+i*.2)/9.81))**2})); return <Frame title="Simple Pendulum • measurement rig" emoji="◉" kind="pendulum" ready={ready} records={records} onRecord={()=>setRecords([...records,{a:`L = ${L.toFixed(2)} m`,b:`T = ${period.toFixed(3)} s`}])} steps={[{title:'Rig',description:'Drag string and bob'},{title:'Set length',description:'Pull bob vertically'},{title:'Release',description:'Drag bob sideways then release'},{title:'Time',description:'Record period'}]} observations={['The bob is pulled directly on the lab rig.', 'The T²–L graph gives g from its gradient.']} tutor="Drag the bob sideways in the rig to set its release angle. A low amplitude keeps the small-angle model accurate." controls={<><Palette items={['Tripod','String','Bob','Photogate']} placed={placed} setPlaced={setPlaced}/><button onClick={()=>setRun(!run)} className="w-full rounded-lg bg-cyan-600 py-2 text-sm font-bold text-white">{run?'Stop timer':'Release bob & start timer'}</button><p className="text-xs">Length {L.toFixed(2)} m · Timer {t.toFixed(2)} s · T {period.toFixed(3)} s</p></>} visualization={<><svg viewBox="0 0 400 260" className="w-full rounded-xl bg-sky-50" onPointerMove={e=>{if(!run&&e.buttons){const r=e.currentTarget.getBoundingClientRect();setL(clamp((e.clientY-r.top)/r.height*1.6,.25,1.8));setTheta(clamp((e.clientX-r.left)/r.width*100-50,-45,45))}}}><rect x="150" y="16" width="100" height="10" rx="4" fill="#475569"/><line x1="200" y1="28" x2={bx} y2={by} stroke="#334155" strokeWidth="3"/><circle cx={bx} cy={by} r="18" fill="#0ea5e9"/><text x="20" y="235" fontSize="12" fill="#334155">Drag bob to set length and angle</text></svg><SvgGraph title="Automatic T² vs L" yLabel="T² (s²)" series={[{name:'T²',points:graph}]}/></>} />}

export function ProjectileLab(){const [placed,setPlaced]=useState([]),[angle,setAngle]=useState(45),[v,setV]=useState(28),[g,setG]=useState(9.81),[run,setRun]=useState(false),[clock,setClock]=useState(0),[records,setRecords]=useState([]);const ref=useRef();const rad=angle*Math.PI/180,vx=v*Math.cos(rad),vy=v*Math.sin(rad),T=2*vy/g,R=vx*T,H=vy*vy/(2*g);const ready=placed.includes('Cannon')&&placed.includes('Projectile');useEffect(()=>{if(!run)return;const start=performance.now();const f=n=>{const z=(n-start)/700;if(z>=T){setClock(T);setRun(false);return}setClock(z);ref.current=requestAnimationFrame(f)};ref.current=requestAnimationFrame(f);return()=>cancelAnimationFrame(ref.current)},[run,T]);const pts=Array.from({length:80},(_,i)=>{const q=i/79*T;return{x:vx*q,y:Math.max(0,vy*q-.5*g*q*q)}});const ball={x:vx*clock,y:Math.max(0,vy*clock-.5*g*clock*clock)}; return <Frame title="Projectile Motion • launch range" emoji="◢" kind="projectile" ready={ready} records={records} onRecord={()=>setRecords([...records,{a:`${v} m/s @ ${angle}°`,b:`R ${R.toFixed(1)} m · H ${H.toFixed(1)} m`}])} steps={[{title:'Place',description:'Drag cannon and projectile'},{title:'Aim',description:'Rotate barrel directly'},{title:'Launch',description:'Fire and track'},{title:'Analyse',description:'Record measurements'}]} observations={['The range detector measures landing position.', 'Plots update from the actual launch state.']} tutor="Drag across the cannon viewport to aim; drag vertically to set launch speed. Use gravity control for other worlds." controls={<><Palette items={['Cannon','Projectile','Range sensor']} placed={placed} setPlaced={setPlaced}/><button onClick={()=>{setClock(0);setRun(true)}} className="w-full rounded-lg bg-rose-600 py-2 text-sm font-bold text-white">Launch projectile</button><div className="grid grid-cols-3 text-xs"><span>Angle {angle}°</span><span>Velocity {v} m/s</span><span>g {g.toFixed(1)}</span></div><input aria-label="gravity" className="w-full" type="range" min="3" max="15" step=".1" value={g} onChange={e=>setG(+e.target.value)}/></>} visualization={<><svg viewBox="0 0 520 230" className="w-full rounded-xl bg-sky-50" onPointerMove={e=>{if(!run&&e.buttons){const r=e.currentTarget.getBoundingClientRect();setAngle(clamp((r.bottom-e.clientY)/r.height*85,10,80));setV(clamp((e.clientX-r.left)/r.width*55,8,60))}}}><line x1="20" y1="205" x2="500" y2="205" stroke="#65a30d" strokeWidth="3"/>{pts.map((p,i)=><circle key={i} cx={20+p.x/R*460} cy={205-p.y/Math.max(H,1)*160} r="1" fill="#94a3b8"/>)}<circle cx={20+ball.x/R*460} cy={205-ball.y/Math.max(H,1)*160} r="7" fill="#f43f5e"/><text x="22" y="26" fontSize="12">drag to aim/charge</text></svg><SvgGraph title="Position & velocity over time" yLabel="m, m/s" series={[{name:'position',points:pts.map((p,i)=>({x:i/79*T,y:p.y}))},{name:'velocity',points:pts.map((p,i)=>({x:i/79*T,y:vy-g*i/79*T}))}]}/></>} />}

export function HysteresisLab(){const [field,setField]=useState(0),[records,setRecords]=useState([]);const pts=Array.from({length:100},(_,i)=>{const h=-3+i*6/99;return{x:h,y:Math.tanh((h-field*.3)*1.4)+(h>0?.13:-.13)}});return <Frame title="Magnetic Hysteresis • material analyser" emoji="🧲" kind="hysteresis" ready records={records} onRecord={()=>setRecords([...records,{a:`H = ${field.toFixed(2)} A/m`,b:`B = ${Math.tanh(field).toFixed(3)} T`}])} steps={[{title:'Mount core',description:'Place sample in coil'},{title:'Sweep H',description:'Move field control'},{title:'Inspect domains',description:'Watch alignment'},{title:'Record',description:'Capture loop'}]} observations={['Retentivity is the B field remaining at H = 0.', 'Coercivity is the reverse field needed to demagnetize.']} tutor="Sweep the magnetic field through both directions. Domain arrows align as H increases; the offset produces the B–H loop." controls={<><label className="text-xs">Drag field handle H = {field.toFixed(2)} A/m<input className="w-full" type="range" min="-3" max="3" step=".05" value={field} onChange={e=>setField(+e.target.value)}/></label><div className="grid grid-cols-8 gap-1">{Array.from({length:24},(_,i)=><span key={i} className="h-5 rounded bg-violet-500 transition-transform" style={{transform:`rotate(${field*28+(i%3)*8}deg)`,opacity:.45+Math.abs(field)/6}} />)}</div><p className="text-xs">Retentivity ≈ 0.13 T · Coercivity ≈ 0.18 A/m</p></>} visualization={<SvgGraph title="Real-time B–H loop" yLabel="B (T)" series={[{name:'B(H)',points:pts}]}/>} />}

export function DiodeLab(){const [placed,setPlaced]=useState([]),[level,setLevel]=useState(2),[mode,setMode]=useState('clip'),[records,setRecords]=useState([]);const ready=['Diode','Resistor','Source','Wire'].every(x=>placed.includes(x));const points=Array.from({length:120},(_,i)=>{const x=i/119*4*Math.PI,vin=5*Math.sin(x);return{x:i,y:mode==='clip'?Math.min(vin,level+.7):vin+level+5}});const input=Array.from({length:120},(_,i)=>({x:i,y:5*Math.sin(i/119*4*Math.PI)}));return <Frame title="Diode Clipping & Clamping • breadboard" emoji="∿" kind="diode" ready={ready} records={records} onRecord={()=>setRecords([...records,{a:`${mode} at ${level} V`,b:`Vout peak ${Math.max(...points.map(p=>p.y)).toFixed(1)} V`}])} steps={[{title:'Populate',description:'Drag parts onto breadboard'},{title:'Wire',description:'Close the diode circuit'},{title:'Probe',description:'Connect oscilloscope'},{title:'Record',description:'Store waveform'}]} observations={['The oscilloscope compares input and output in real time.', 'Silicon diode drop is included as 0.7 V.']} tutor="Populate the breadboard in the correct order: source → resistor → diode → return. The scope appears once the circuit is complete." controls={<><Palette items={['Source','Resistor','Diode','Capacitor','Wire','Oscilloscope']} placed={placed} setPlaced={setPlaced}/><div className="flex gap-2"><button onClick={()=>setMode('clip')} className="rounded bg-slate-800 px-3 py-2 text-xs text-white">Clip</button><button onClick={()=>setMode('clamp')} className="rounded bg-slate-800 px-3 py-2 text-xs text-white">Clamp</button></div><label className="text-xs">Drag reference level: {level} V<input className="w-full" type="range" min="0" max="5" step=".1" value={level} onChange={e=>setLevel(+e.target.value)}/></label></>} visualization={<SvgGraph title="Live oscilloscope — input / output" yLabel="voltage (V)" series={[{name:'input',points:input},{name:'output',points}]}/>} />}

export function DoubleSlitLab(){const [slit,setSlit]=useState(.25),[distance,setDistance]=useState(1.5),[records,setRecords]=useState([]);const lambda=550e-9,fringe=lambda*distance/(slit*1e-3)*1000;const intensity=Array.from({length:180},(_,i)=>{const x=(i-90)/18;const beta=Math.PI*.15*x;return{x:i,y:(Math.cos(beta)**2)*(Math.sin(beta*.45)/(beta*.45||1))**2}});return <Frame title="Young’s Double Slit • optical bench" emoji="☀" kind="slit" ready records={records} onRecord={()=>setRecords([...records,{a:`d ${distance.toFixed(2)} m · a ${slit.toFixed(2)} mm`,b:`fringe width ${fringe.toFixed(2)} mm`}])} steps={[{title:'Align',description:'Mount laser and double slit'},{title:'Focus',description:'Drag slit separation'},{title:'Measure',description:'Move screen ruler'},{title:'Record',description:'Capture fringe width'}]} observations={['Bright and dark fringes are rendered from the interference equation.', 'Use the on-screen ruler to measure adjacent bright fringe spacing.']} tutor="Drag the slit control and screen distance. The illuminated screen updates with the real wavelength, separation and distance relationship." controls={<><label className="text-xs">Drag slit separation: {slit.toFixed(2)} mm<input className="w-full" type="range" min=".08" max=".8" step=".01" value={slit} onChange={e=>setSlit(+e.target.value)}/></label><label className="text-xs">Screen distance: {distance.toFixed(2)} m<input className="w-full" type="range" min=".5" max="3" step=".05" value={distance} onChange={e=>setDistance(+e.target.value)}/></label><p className="text-xs">Ruler measurement: β = {fringe.toFixed(2)} mm</p></>} visualization={<><div className="flex h-24 items-stretch overflow-hidden rounded bg-slate-950">{intensity.map((p,i)=><span key={i} className="flex-1" style={{background:`rgba(250,204,21,${clamp(p.y,0,1)})`}} />)}</div><SvgGraph title="Intensity distribution on screen" yLabel="relative intensity" series={[{name:'I(x)',points:intensity}]}/></>} />}
