import { useMemo, useRef, useState } from 'react'
import { Canvas } from '@react-three/fiber'
import { ContactShadows, Environment, OrbitControls, RoundedBox } from '@react-three/drei'
import { Download, FileText, MoveHorizontal, RotateCcw, Save } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { jsPDF } from 'jspdf'

const LC = 0.02
const specimens = [
  { id: 'sphere', name: 'Steel sphere', size: 25.00, type: 'external', color: '#77a8df' },
  { id: 'cube', name: 'Calibration cube', size: 30.00, type: 'external', color: '#c79455' },
  { id: 'cylinder', name: 'Aluminium cylinder', size: 29.82, type: 'external', color: '#b6c2ce' },
  { id: 'pipe', name: 'Copper pipe', size: 18.36, type: 'internal', color: '#c77645' },
  { id: 'wire', name: 'Copper wire', size: 3.18, type: 'external', color: '#c77645' },
  { id: 'coin', name: 'Laboratory coin', size: 22.50, type: 'external', color: '#d5b651' },
  { id: 'bolt', name: 'Hex bolt', size: 12.00, type: 'external', color: '#8793a0' },
  { id: 'nut', name: 'Hex nut', size: 14.00, type: 'internal', color: '#8b98a4' },
  { id: 'pcb', name: 'PCB step', size: 8.75, type: 'step', color: '#438d72' },
]
const clamp = (v, a, b) => Math.min(b, Math.max(a, v))

function Specimen3D({ specimen }) {
  const width = Math.max(.12, specimen.size / 10); const position = [-2.15 + width / 2, .28, 0]
  const material = <meshStandardMaterial color={specimen.color} metalness={.72} roughness={.22} />
  if (specimen.id === 'sphere') return <mesh position={position} castShadow><sphereGeometry args={[width / 2, 40, 24]} />{material}</mesh>
  if (['cylinder', 'coin', 'pipe'].includes(specimen.id)) return <mesh position={position} rotation={[0, 0, Math.PI / 2]} castShadow><cylinderGeometry args={[width / 3.2, width / 3.2, width, 40]} />{material}</mesh>
  if (specimen.id === 'wire') return <mesh position={position} rotation={[0, 0, Math.PI / 2]} castShadow><cylinderGeometry args={[.055, .055, width, 24]} />{material}</mesh>
  if (['bolt', 'nut'].includes(specimen.id)) return <mesh position={position} rotation={[0, 0, Math.PI / 2]} castShadow><cylinderGeometry args={[width / 3, width / 3, width, 6]} />{material}</mesh>
  return <RoundedBox args={[width, Math.max(.22, width * .55), .42]} radius={.04} position={position} castShadow>{material}</RoundedBox>
}

function CaliperScene({ opening, specimen, onOpening }) {
  const slide = opening / 10 - 2.15
  const dragJaw = event => { if (event.buttons === 1) { event.stopPropagation(); onOpening(clamp((event.point.x + 2.15) * 10, 0, 52)) } }
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3 text-xs"><span className="font-semibold text-slate-700">3D direct-manipulation instrument</span><span className="text-slate-500">Drag cyan slider · orbit, zoom and pan the scene</span></div><div className="h-[390px]"><Canvas shadows camera={{ position: [6.7, 3.8, 6.8], fov: 38 }}><color attach="background" args={['#ffffff']} /><ambientLight intensity={.85} /><directionalLight position={[4, 7, 5]} intensity={2.1} castShadow shadow-mapSize={[1024, 1024]} /><Environment preset="city" /><group>{/* precision beam */}<RoundedBox args={[6.1, .26, .38]} radius={.035} position={[.9, 0, 0]} castShadow><meshStandardMaterial color="#b9c4cc" metalness={.94} roughness={.16} /></RoundedBox>{Array.from({ length: 51 }, (_, i) => <mesh key={i} position={[-2.1 + i * .12, .2, .21]}><boxGeometry args={[.012, i % 10 === 0 ? .34 : .17, .02]} /><meshStandardMaterial color="#334155" /></mesh>)}{/* fixed jaw */}<RoundedBox args={[.22, 1.65, .42]} radius={.03} position={[-2.15, .78, 0]} castShadow><meshStandardMaterial color="#aeb9c2" metalness={.9} roughness={.18} /></RoundedBox><RoundedBox args={[.72, .18, .42]} radius={.025} position={[-1.84, 1.48, 0]}><meshStandardMaterial color="#aeb9c2" metalness={.9} roughness={.18} /></RoundedBox>{/* movable jaw */}<group position={[slide, 0, 0]} onPointerMove={dragJaw}><RoundedBox args={[.25, 1.46, .52]} radius={.04} position={[0, .67, 0]} castShadow><meshStandardMaterial color="#0891b2" metalness={.76} roughness={.2} /></RoundedBox><RoundedBox args={[.76, .18, .48]} radius={.03} position={[-.33, 1.25, 0]}><meshStandardMaterial color="#22d3ee" metalness={.5} roughness={.25} /></RoundedBox><RoundedBox args={[1.18, .45, .6]} radius={.06} position={[.22, -.13, 0]}><meshStandardMaterial color="#e0f2fe" metalness={.58} roughness={.2} /></RoundedBox>{Array.from({ length: 11 }, (_, i) => <mesh key={i} position={[i * .08 - .36, .15, .32]}><boxGeometry args={[.01, i % 5 === 0 ? .18 : .1, .012]} /><meshStandardMaterial color="#0f172a" /></mesh>)}</group><Specimen3D specimen={specimen} /></group><mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -.48, 0]} receiveShadow><planeGeometry args={[18, 14]} /><shadowMaterial opacity={.13} /></mesh><ContactShadows position={[0, -.47, 0]} opacity={.2} scale={13} blur={2.5} /><OrbitControls enablePan enableZoom minDistance={4.5} maxDistance={11} /></Canvas></div></div>
}

function CaliperWorkbench({ opening, specimen, onOpening }) {
  const ref = useRef(null); const [dragging, setDragging] = useState(false)
  const left = 110, unit = 10.7, jaw = left + opening * unit, objectWidth = Math.max(12, specimen.size * unit)
  const move = event => { if (!dragging) return; const box = ref.current.getBoundingClientRect(); onOpening(clamp((event.clientX - box.left) / (box.width / 760) / unit - left / unit, 0, 52)) }
  return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3 text-xs"><span className="font-semibold text-slate-700">Drag-and-drop Vernier Caliper</span><span className={dragging ? 'font-semibold text-cyan-700' : 'text-slate-500'}>{dragging ? 'Positioning jaw…' : 'Drag the cyan jaw to the specimen'}</span></div><svg ref={ref} viewBox="0 0 760 300" className="w-full touch-none select-none bg-slate-50" onPointerMove={move} onPointerUp={() => setDragging(false)} onPointerLeave={() => setDragging(false)} role="img" aria-label="Draggable Vernier caliper"><defs><linearGradient id="metal" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#f8fafc"/><stop offset=".5" stopColor="#b6c1cb"/><stop offset="1" stopColor="#64748b"/></linearGradient><radialGradient id="sample"><stop stopColor="#dbeafe"/><stop offset="1" stopColor={specimen.color}/></radialGradient></defs><rect x="44" y="139" width="680" height="25" rx="3" fill="url(#metal)"/><rect x="44" y="164" width="680" height="10" fill="#64748b" opacity=".65"/>{Array.from({length: 53},(_,i)=><g key={i}><line x1={left+i*unit} x2={left+i*unit} y1="139" y2={i%10===0?105:i%5===0?116:125} stroke="#334155" strokeWidth="1"/>{i%10===0&&<text x={left+i*unit} y="100" fontSize="10" textAnchor="middle" fill="#475569">{i}</text>}</g>)}<path d="M72 50 H105 V236 H70 V80 H72Z" fill="url(#metal)" stroke="#475569"/><path d="M70 111 H129 V139 H70Z" fill="url(#metal)" stroke="#475569"/><path d="M78 216 H102 V267 H91 V230 H78Z" fill="#64748b"/><g transform={`translate(${jaw-left},0)`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setDragging(true)}} className="cursor-ew-resize"><path d="M110 55 H143 V232 H107 V82 H110Z" fill="#0891b2" stroke="#164e63"/><path d="M105 111 H162 V139 H105Z" fill="#22d3ee" stroke="#164e63"/><rect x="96" y="164" width="190" height="45" rx="5" fill="#e0f2fe" stroke="#0891b2"/>{Array.from({length:51},(_,i)=><line key={i} x1={108+i*3.55} x2={108+i*3.55} y1="164" y2={i%10===0?198:188} stroke="#0f172a"/>)}<rect x="166" y="215" width="52" height="20" rx="10" fill="#0f766e"/><circle cx="192" cy="225" r="7" fill="#fef3c7" stroke="#a16207"/></g><g transform={`translate(${jaw-objectWidth},0)`}><circle cx={objectWidth/2} cy="205" r={Math.max(9,objectWidth/2)} fill="url(#sample)" stroke="#334155" strokeWidth="2"/>{specimen.id==='pipe'&&<circle cx={objectWidth/2} cy="205" r={Math.max(4,objectWidth/5)} fill="#fff" stroke="#334155" strokeWidth="2"/>}</g><line x1="46" x2="724" y1="270" y2="270" stroke="#cbd5e1"/><text x="46" y="289" fontSize="11" fill="#64748b">Main scale · 0 mm</text><text x="650" y="289" fontSize="11" fill="#64748b">50 mm</text></svg></div>
}

function Metric({ label, value, unit = 'mm' }) { return <div className="border-l border-slate-200 px-3"><p className="text-[10px] font-medium uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 font-mono text-lg font-bold text-slate-900">{value}<span className="ml-1 text-xs font-normal text-slate-400">{unit}</span></p></div> }

export default function VernierCaliper() {
  const [specimenId, setSpecimenId] = useState('sphere'), [opening, setOpening] = useState(25), [zeroError, setZeroError] = useState(0), [history, setHistory] = useState([]), [labMode, setLabMode] = useState('practice')
  const specimen = specimens.find(item => item.id === specimenId)
  const raw = Math.round(opening / LC) * LC; const msr = Math.floor(raw); const vsd = Math.round((raw - msr) / LC) % 50; const reading = raw - zeroError; const error = reading - specimen.size; const accuracy = Math.max(0, 100 - Math.abs(error / specimen.size) * 100); const aligned = Math.abs(error) <= .05
  const assistant = specimen.type !== 'external' ? `Use ${specimen.type} jaws for ${specimen.name}. The visual jaw is currently configured for external measurement, so this trial should be treated as a setup check.` : aligned ? 'Excellent contact: both jaw faces are tangent to the specimen. Record this observation.' : error > 0 ? 'The movable jaw has passed the contact surface. Drag it gently left until it just touches the specimen.' : 'The jaws are not in contact yet. Drag the movable jaw right until it meets the specimen without squeezing.'
  const selectSpecimen = id => { const next = specimens.find(item => item.id === id); setSpecimenId(id); setOpening(next.size); }
  const record = () => setHistory(old => [...old, { trial: old.length + 1, reading: +reading.toFixed(2), error: +error.toFixed(2), accuracy: +accuracy.toFixed(1), object: specimen.name }])
  const csv = () => { const body = ['Trial,Object,Corrected reading (mm),Error (mm),Accuracy (%)', ...history.map(r => `${r.trial},${r.object},${r.reading},${r.error},${r.accuracy}`)].join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([body], { type: 'text/csv' })); a.download = 'vernier-observations.csv'; a.click(); URL.revokeObjectURL(a.href) }
  const pdf = () => { const doc = new jsPDF(); doc.text('CurioLabs Vernier Caliper Lab Report', 15, 18); doc.text(`Specimen: ${specimen.name}`, 15, 28); history.forEach((r, i) => doc.text(`${r.trial}. ${r.reading} mm | error ${r.error} mm | ${r.accuracy}%`, 15, 40 + i * 8)); doc.save('vernier-lab-report.pdf') }
  const readout = useMemo(() => `MSR ${msr} mm + VSR ${vsd} × ${LC} mm − zero error ${zeroError.toFixed(2)} mm`, [msr, vsd, zeroError])
  return <div className="min-h-[100dvh] bg-slate-50 text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><div><Link to="/physics" className="text-xs font-semibold text-cyan-700">← Physics Lab</Link><h1 className="font-display text-lg font-bold">Virtual Vernier Caliper Laboratory</h1></div><div className="flex gap-2">{['practice','guided','exam'].map(m => <button key={m} onClick={() => setLabMode(m)} className={`rounded-lg px-3 py-1.5 text-xs font-bold capitalize ${labMode === m ? 'bg-slate-900 text-white' : 'border border-slate-200 bg-white text-slate-600'}`}>{m}</button>)}</div></div></header>
    <main className="mx-auto max-w-7xl p-4 md:p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-cyan-700">Precision measurement workstation</p><p className="mt-1 text-sm text-slate-500">Grab the blue moving jaw directly. The scales and contact assessment update continuously.</p></div><div className="grid gap-5 xl:grid-cols-[230px_minmax(0,1fr)_270px]">
      <aside className="space-y-4"><section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-bold">Specimen tray</h2><div className="mt-3 grid grid-cols-2 gap-2">{specimens.map(s => <button key={s.id} onClick={() => selectSpecimen(s.id)} className={`rounded-lg border p-2 text-left text-xs ${s.id === specimenId ? 'border-cyan-600 bg-cyan-50' : 'border-slate-200 hover:border-slate-300'}`}><span className="block font-bold">{s.name}</span><span className="text-slate-500">{s.type}</span></button>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-bold">Calibration</h2><label className="mt-3 block text-xs text-slate-600">Zero error: {zeroError.toFixed(2)} mm<input className="mt-2 w-full accent-cyan-700" type="range" min="-.10" max=".10" step=".02" value={zeroError} onChange={e => setZeroError(+e.target.value)}/></label><button onClick={() => setZeroError(0)} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-cyan-700"><RotateCcw size={13}/>Reset zero</button></section></aside>
      <section className="min-w-0 space-y-5"><CaliperWorkbench opening={opening} specimen={specimen} onOpening={setOpening}/><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-sm font-bold"><MoveHorizontal size={17} className="text-cyan-700"/>Physical scale readout</div><div className="mt-4 grid grid-cols-2 gap-y-4 md:grid-cols-5"><Metric label="MSR" value={msr}/><Metric label="VSR" value={vsd} unit="division"/><Metric label="Least count" value={LC.toFixed(2)}/><Metric label="Zero error" value={zeroError.toFixed(2)}/><Metric label="Corrected" value={reading.toFixed(2)}/></div><p className="mt-4 border-t pt-3 font-mono text-xs text-slate-500">{readout}</p></div><div className="grid gap-5 lg:grid-cols-3"><Chart title="Measurement reading" data={history} dataKey="reading" color="#0891b2"/><Chart title="Error analysis" data={history} dataKey="error" color="#ea580c"/><Chart title="Accuracy trend" data={history} dataKey="accuracy" color="#16a34a" domain={[0,100]}/></div></section>
      <aside className="space-y-4"><section className="rounded-xl border border-cyan-100 bg-cyan-50 p-4"><h2 className="text-sm font-bold text-cyan-950">AI lab assistant</h2><p className="mt-2 text-sm leading-relaxed text-cyan-900">{assistant}</p><p className="mt-3 border-t border-cyan-200 pt-3 text-xs text-cyan-800">Viva: How does zero error change the corrected reading?</p></section><section className="rounded-xl border border-slate-200 bg-white p-4"><h2 className="text-sm font-bold">Observation table</h2><p className="mt-1 text-xs text-slate-500">Performance: {history.length ? Math.round(history.reduce((a,b) => a + b.accuracy, 0) / history.length) : 0}%</p><button onClick={record} className="mt-3 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-cyan-700 py-2 text-xs font-bold text-white"><Save size={14}/>Record reading</button><div className="mt-3 max-h-32 overflow-auto text-xs">{history.length ? history.map(r => <div key={r.trial} className="grid grid-cols-3 border-b py-2"><span>#{r.trial}</span><span>{r.reading} mm</span><span className={Math.abs(r.error) <= .05 ? 'text-emerald-700' : 'text-orange-700'}>{r.accuracy}%</span></div>) : <p className="text-slate-400">No readings recorded.</p>}</div><div className="mt-3 flex gap-2"><button onClick={csv} disabled={!history.length} className="flex-1 rounded border py-2 text-xs disabled:opacity-40"><Download size={13} className="mr-1 inline"/>CSV</button><button onClick={pdf} disabled={!history.length} className="flex-1 rounded bg-slate-900 py-2 text-xs text-white disabled:opacity-40"><FileText size={13} className="mr-1 inline"/>PDF</button></div></section></aside>
    </div></main></div>
}

function Chart({ title, data, dataKey, color, domain }) { return <div className="rounded-xl border border-slate-200 bg-white p-3"><p className="text-xs font-bold text-slate-700">{title}</p><div className="h-36"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><XAxis dataKey="trial" tick={{fontSize:10}}/><YAxis domain={domain || ['auto','auto']} tick={{fontSize:10}}/><Tooltip/><Line type="monotone" dataKey={dataKey} stroke={color} strokeWidth={2} dot={{r:3}}/></LineChart></ResponsiveContainer></div></div> }
